server:
  port: 8090
  contextPath:
  
  
spring:
  datasource:
    url: jdbc:h2:mem:calendar
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    platform: h2
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true